### PR TITLE
[FRONT-END] {LOGIN} Main page, incorrect password, forgot password

### LINKED ISSUE #79: [FRONT-END] {LOGIN} - main page
- username/email
- password (can view password too)
- remember account toggle
- sign in button
- forgot your password button
Screenshot 2023-02-08 at 7 53 09 PM

### PR DESCRIPTION
**Pull request by samperezh**
# Summary
This includes the main Login page:
image

Its incorrect password error flow:
image

The forgot-my-password page:
image

And its incorrect email error flow:
image

## Related Issues

Which issues does this PR resolve/work on?
Closes #79 #80 #81

### CODE REVIEW

File: frontend/src/Components/LogIn/Main/PasswordTextField.tsx [hunk 1]
```diff
@@ -0,0 +1,37 @@
+import { Input, InputAdornment, IconButton } from "@mui/material";
+import { Visibility, VisibilityOff } from "@material-ui/icons";
```
Comment (selenajin99) [inline frontend/src/Components/LogIn/Main/PasswordTextField.tsx]: can we change to react icons to be consistent with the rest of the app?

**Review by selenajin99 — APPROVED** [review]
